version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static
      - media:/app/media

  nginx:
      build: ./nginx
      volumes:
        - static:/app/static
        - media:/app/media
      restart: always
      ports:
        - "80:80"
      depends_on:
        - web

volumes:
  static:
  media:
