version: '3'

services:
  web:
    image: kwdockerhub/web:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static
      - media:/app/media
      - database:/app/database

  nginx:
    image: kwdockerhub/nginx:latest
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  media:
  database:
